name: Multiverse-NetherPortals
description: Adds Portal support for Multiverse-Core.
authors: ['Rigby', 'fernferret']
version: 4.2.2

main: com.onarandombox.MultiverseNetherPortals.MultiverseNetherPortals
api-version: 1.12.2

depend: ['Multiverse-Core']
softdepend: ['Multiverse-Portals']

commands:
  mvnp:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpl:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpli:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnplist:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpu:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnps:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnplink:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpunlink:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvnpshow:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>